### ISSUE TITLE
Menu item broken on Magento 2.3.3

### ISSUE THREAD

**Issue by itsolon** [kiwicommerce/magento2-cron-scheduler#13]
### Preconditions
We have Magento 2.3.3 on php 7.2 with mariadb 10.4 on Ubuntu 18.04

### Steps to reproduce
install software via composer

### Expected result
running

### Actual result
it works but menu item is broken or bad formatted

### Remark ###
at the moment i would say it has nothing do do that mageplaza has formattet their menu item too

![great](https://user-images.githubusercontent.com/10437947/68322032-fd353700-00c2-11ea-9fab-8bf3f27c16b9.PNG)

**Comment by Darkwolf81** [comment]
I have the same issue. The broken menu came with Magento 2.3.3, it worked on Magento 2.3.2.

**Comment by itsolon** [comment]
![CDATA[<span class="kiwiCommerce-logo">

its because they want to have a nice logo in the menu
<magento-root>/vendor/kiwicommerce/module-cron-scheduler/etc/adminhtml/system.xml
LINE 19

FROM:
<label><![CDATA[<span class="kiwiCommerce-logo">KiwiCommerce Extensions</span>]]></label>

TO:
<label>KiwiCommerce Extensions</label>

then only text logo will remain!

**Comment by kiwi-commerce** [comment]
Hello @itsolon and @Darkwolf81 , Thank you for your report.
The issue has been fixed.

Related commit(s):
26dd694351a39fdf9eacf941d7fec54831af5c6e
45ddd9a2ef480940320ee0822541eaf29a8ffc0e

**Comment by mtytula** [comment]
@kiwi-commerce, any info about releasing this fix? On the newest 1.0.5 version this problem is still present.

**Comment by bheindl** [comment]
@kiwi-commerce Any update on this? When will be the next release, that we get the latest fixes via composer installation?

**Comment by itsolon** [comment]
i just installed freshly issue still there, nothing fixed
